# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.


# BMVC2021 colours:
# #9E005D
# 158, 0, 93
# #7F004B
# #5F003B
# #DC0082


timezone: Europe/London
title: The 35th British Machine Vision Conference 2024
formatted-title: The 35<sup>th</sup> British Machine Vision Conference
brand: BMVC&thinsp;2024
short-title: "BMVC 2024"
conf_year: 2024
email: bmvc@bmvc2024.org
#bmvc2024@googlegroups.com
description: >- # this means to ignore newlines until "baseurl:"
  The website is for the 35th British Machine Vision Conference. 25th - 28th November 2024, Glasgow, UK.
#baseurl: "/BMVC2021" #"/~nc537/bmvc_test" # "/bmva-website" # the subpath of your site, e.g. /blog
#url: "https://britishmachinevisionassociation.github.io" #"http://cs.bath.ac.uk" # the base hostname & protocol for your site, e.g. http://example.com
#baseurl: "/"
#url: "http://bmvc2021.ndfcampbell.org"
baseurl: ""
url: "https://www.bmvc2024.org"
conf-url: "https://www.bmvc2024.org"
chat-url: "https://chat.bmvc2024.org"
logo: "/assets/images/layout/bmvc-2024.png"
#twitter_username: BMVCconf
twitter_username: BMVCconf
github_username:  BritishMachineVisionAssociation
#facebook_username: thebmva
#youtube_channel: channel/UCBDkH5yK4GyVoRkV8lYdwdw1

deadline-time: "23:59 GMT"

#cmt-url: "https://cmt3.research.microsoft.com/BMVC2023/"
bmva-event-url: "https://britishmachinevisionassociation.github.io/meetings/21-09-06-september-event"

dates: 25<sup>th</sup> - 28<sup>th</sup> November 2024

author: BMVC PCs

#flickr_user: '131006004@N06'
#flickr_api_key: adb4be93419edab991522b4fa92b7029

# Handling Reading
safe: true
encoding: utf-8
# markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

#  - jekyll-liquid


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - assets/multipagethumb.sh
  - assets/thumbnail_script.sh
  - copy_to_aws.sh
  - old/
  - conference/
  - programme/oral.md
  - programme/paper-awards.md
  - programme/accepted-papers.md
  - programme/papers.md
  - programme/poster.md
  - programme/programme.md
  - programme/schedule.md
  - programme/workshop_papers.md
  - proceedings/create_all.py
  - proceedings/CameraReadyPapers.py
  # - proceedings/workshop-proceedings.md
  # - programme/workshops.md
  - old_index.md
  - attending/guides.md
  # - attending/code-of-conduct.md
  - attending/about-the-city.md
  # - attending/plan-your-visit.md
  - attending/student-funding.md
  - attending/registration_old.md
  - sponsorship_backup.md
  # - authors/instructions-for-presenting-authors.md
  - index_v0.md
  # - calls/doctoral-consortium.md
  - authors/rebuttal-instructions.md
  # - authors/reviewing-guidelines-new.md
  - authors/faq.md
  - authors/submit-your-paper-old.md
  - authors/reviewing-guidelines-old.md
  # - authors/area-chair-guidelines.md
  - people/area-chairs.md
  - people/emergency-reviewers.md
  - people/volunteers.md

#main_sponsors:
#  - name: IAPR
#    url: http://www.iapr.org/
#    logo: /img/affiliates/logo-iapr.png
#sponsors:
#  - name: BCS
#    url: http://bcs.org.uk/
#    logo: /img/affiliates/logo-bcs.png
#  - name: IET
#    url: http://www.theiet.org/
#    logo: /img/affiliates/logo-iet.jpg
#  - name: UKIVA
#    url: http://www.ukiva.org/
#    logo: /img/affiliates/logo-ukiva.jpg
#  - name: AVA
#    url: http://www.theava.net/
#    logo: /img/affiliates/logo-ava.jpg
# webrick:
#   headers:
#     content-disposition: attachment